# Custom Preprocessing
In this example, we demonstrate how to use custom preprocessing steps in the model object. We show how to split the input features and define a custom preprocessing /feature selection routine.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn import pipeline as sklearn_pipeline
from sklearn.model_selection import GroupKFold

import mother.ml as ml
from mother.cv import core
from mother import feature_generation as fg

from mother.preprocessing import SmilesToMolTransformer, StandardizerTransformer

## Usual regression workflow
.. as pointed out in the regression example. However, we add a string-column to the dataset. This column could be used as a categoric feature in the model, however, for demonstration pruposes we show in this example how to handle this column in a custom preprocessing pipeline in the "model" object.

In [2]:
input_file: Path = Path("../freesolv_train.csv")
data: pd.DataFrame = pd.read_csv(input_file, sep=",")
data = data.head(100)  # limit data to 100 rows for testing
data = data[["iupac", "smiles", "expt"]]

In [3]:
# add a string column to the data
rng = np.random.default_rng(42)
data["string_col"] = rng.choice(["A", "B", "C"], data.shape[0])

In [4]:
data

,iupac,smiles,expt,string_col
0,"4-methoxy-N,N-dimethyl-benzamide",CN(C)C(=O)c1ccc(cc1)OC,-11.01,A
1,methanesulfonyl chloride,CS(=O)(=O)Cl,-4.87,C
2,3-methylbut-1-ene,CC(C)C=C,1.83,B
3,2-ethylpyrazine,CCc1cnccn1,-5.45,B
4,heptan-1-ol,CCCCCCCO,-4.21,B
5,"3,5-dimethylphenol",Cc1cc(cc(c1)O)C,-6.27,C
6,"2,3-dimethylbutane",CC(C)C(C)C,2.34,A
7,2-methylpentan-2-ol,CCCC(C)(C)O,-3.92,C
8,"1,2-dimethylcyclohexane",C[C@@H]1CCCC[C@@H]1C,1.58,A
9,butan-2-ol,CC[C@H](C)O,-4.62,A
10,dibromomethane,C(Br)Br,-1.96,B
11,2-methylpentan-3-ol,CC[C@H](C(C)C)O,-3.88,C
12,2-ethylpyridine,CCc1ccccn1,-4.33,C
13,ethyl pentanoate,CCCCC(=O)OCC,-2.49,C
14,benzenethiol,c1ccc(cc1)S,-2.55,C
15,"(2Z)-3,7-dimethylocta-2,6-dien-1-ol",CC(=CCC/C(=C\CO)/C)C,-4.78,C
16,indane,c1ccc2c(c1)CCC2,-1.46,B
17,ethoxybenzene,CCOc1ccccc1,-2.22,A
18,4-bromophenol,c1cc(ccc1O)Br,-5.85,C
19,"2,2-dimethylpentane",CCCC(C)(C)C,2.88,B
20,2-acetoxyethyl acetate,CC(=O)OCCOC(=O)C,-6.34,B
21,ethion,CCOP(=S)(OCC)SCSP(=S)(OCC)OCC,-6.10,B
22,cycloheptanol,C1CCCC(CC1)O,-5.48,A
23,methyl cyclopropanecarboxylate,COC(=O)C1CC1,-4.10,C
24,benzonitrile,c1ccc(cc1)C#N,-4.10,C
25,pentanenitrile,CCCCC#N,-3.52,B
26,2-methylpropan-2-ol,CC(C)(C)O,-4.47,B
27,"2,4-dimethylpentan-3-one",CC(C)C(=O)C(C)C,-2.74,C
28,propanal,CCC=O,-3.43,B
29,"N,N-dimethylformamide",CN(C)C=O,-7.81,B
30,p-xylene,Cc1ccc(cc1)C,-0.80,B
31,"penta-1,4-diene",C=CCC=C,0.93,A
32,"2-(2,3-dimethylphenyl)aminobenzoic acid",Cc1cccc(c1C)Nc2ccccc2C(=O)O,-6.78,A
33,"N,N-dimethylbenzamide",CN(C)C(=O)c1ccccc1,-9.29,B
34,N-ethylethanamine,CCNCC,-4.07,C
35,4-tert-butylphenol,CC(C)(C)c1ccc(cc1)O,-5.91,A
36,isopentyl formate,CC(C)CCOC=O,-2.13,C
37,decan-1-ol,CCCCCCCCCCO,-3.64,C
38,ethyl propanoate,CCC(=O)OCC,-2.68,A
39,nonane,CCCCCCCCC,3.13,B
40,N-methylacetamide,CC(=O)NC,-10.00,A
41,non-1-ene,CCCCCCCC=C,2.06,C
42,naphthalen-2-ol,c1ccc2cc(ccc2c1)O,-8.11,C
43,"1,2,4-trichlorobenzene",c1cc(c(cc1Cl)Cl)Cl,-1.12,B
44,"(2R,3R,4R,5R)-Hexan-1,2,3,4,5,6-hexol",C([C@H]([C@H]([C@@H]([C@@H](CO)O)O)O)O)O,-23.62,A
45,methyl butanoate,CCCC(=O)OC,-2.83,C
46,2-hydroxybenzaldehyde,c1ccc(c(c1)C=O)O,-4.68,B
47,azetidine,C1CNC1,-5.56,C
48,N-propylpropan-1-amine,CCCNCCC,-3.65,C
49,aniline,c1ccc(cc1)N,-5.49,C

In [5]:
preprocessor: sklearn_pipeline.Pipeline = sklearn_pipeline.Pipeline(
    [
        (
            "smiles_standardizer",
            StandardizerTransformer(flags=["STANDARDIZE", "DESALT", "NEUTRALIZE"]),
        ),
        ("smiles_to_mol", SmilesToMolTransformer()),
        # Add other column transformations here if needed
    ],
    memory=None,
).set_output(transform="pandas")

structure_data: pd.Series = data["smiles"]
mol_data: pd.DataFrame = preprocessor.fit_transform(structure_data)

[08:10:59] Initializing Normalizer
[08:10:59] Initializing Normalizer
[08:10:59] Initializing Normalizer
[08:10:59] Initializing MetalDisconnector
[08:10:59] Initializing Normalizer
[08:10:59] Initializing MetalDisconnector
[08:10:59] Initializing Normalizer

In [6]:
feature_generator = sklearn_pipeline.FeatureUnion(
    transformer_list=[
        ("maccs", fg.MaccsFingerprints()),
        ("morgan", fg.MorganFingerprints()),
        ("desc", fg.ChemicalDescriptors()),
    ]
).set_output(transform="pandas")


features: pd.DataFrame = feature_generator.fit_transform(mol_data["Molecule"])

Use one of the available strategies to define groups for cross-validation.

In [7]:
# cv grouping
groups_engine = core.HdbscanGroupingFromMols(scaffold="Murcko", radius=2, fp_size=2048, include_chirality=False)

groups: pd.DataFrame = groups_engine.set_output(transform="pandas").fit_transform(mol_data["Molecule"])
groups.head()

cv = GroupKFold(n_splits=5)

print(f"{groups['hdbscan-group'].nunique()} groups found")

3 groups found

## Model Training
The model consists of two steps:
1a. Feature selection using the __FeatureSelector__ for columns from the feature generator
1b. Custom preprocessing for the string column.
2. Model training using the __CatboostRegressorMother__

In [8]:
# defining a dummy custom preprocessing step for the string column. Replace this with your own preprocessing steps, if needed.

from sklearn.base import BaseEstimator, TransformerMixin


class CustomStringPreprocessor(BaseEstimator, TransformerMixin):
    """For demonstration: this is an implementation of a one-hot-encoder for a string column."""

    def __init__(self):
        """
        Initialize the CustomStringPreprocessor.

        This method is intentionally empty as no parameters or state need to be
        initialized. The transformer operates on fixed categories ['A', 'B', 'C']
        and doesn't require configuration.
        """
        pass

    def fit(self, X, y=None):  # noqa: ARG002 - y parameter required for sklearn compatibility
        self.is_fitted_ = True  # tell sklearn that the transformer is fitted
        return self

    def transform(self, X: np.ndarray) -> np.ndarray:
        Y = np.zeros((X.shape[0], 3))
        for i, x in enumerate(X):
            if x == "A":
                Y[i, 0] = 1
            elif x == "B":
                Y[i, 1] = 1
            elif x == "C":
                Y[i, 2] = 1
        return Y

    def get_feature_names_out(self, *args, **kwargs) -> list:  # noqa: ARG002 - parameters required for compatibility
        return [f"OHE_{i}" for i in ("A", "B", "C")]

In [9]:
# test the object
prep: TransformerMixin = CustomStringPreprocessor().set_output(transform="pandas")
prep.fit_transform(data["string_col"])

    OHE_A  OHE_B  OHE_C
0     1.0    0.0    0.0
1     0.0    0.0    1.0
2     0.0    1.0    0.0
3     0.0    1.0    0.0
4     0.0    1.0    0.0
5     0.0    0.0    1.0
6     1.0    0.0    0.0
7     0.0    0.0    1.0
8     1.0    0.0    0.0
9     1.0    0.0    0.0
10    0.0    1.0    0.0
11    0.0    0.0    1.0
12    0.0    0.0    1.0
13    0.0    0.0    1.0
14    0.0    0.0    1.0
15    0.0    0.0    1.0
16    0.0    1.0    0.0
17    1.0    0.0    0.0
18    0.0    0.0    1.0
19    0.0    1.0    0.0
20    0.0    1.0    0.0
21    0.0    1.0    0.0
22    1.0    0.0    0.0
23    0.0    0.0    1.0
24    0.0    0.0    1.0
25    0.0    1.0    0.0
26    0.0    1.0    0.0
27    0.0    0.0    1.0
28    0.0    1.0    0.0
29    0.0    1.0    0.0
30    0.0    1.0    0.0
31    1.0    0.0    0.0
32    1.0    0.0    0.0
33    0.0    1.0    0.0
34    0.0    0.0    1.0
35    1.0    0.0    0.0
36    0.0    0.0    1.0
37    0.0    0.0    1.0
38    1.0    0.0    0.0
39    0.0    1.0    0.0
40    1.0    0.0    0.0
41    0.0    0.0    1.0
42    0.0    0.0    1.0
43    0.0    1.0    0.0
44    1.0    0.0    0.0
45    0.0    0.0    1.0
46    0.0    1.0    0.0
47    0.0    0.0    1.0
48    0.0    0.0    1.0
49    0.0    0.0    1.0

In [10]:
# Use the skl ColumnTransformer to combine the custom preprocessing with the usual feature selection
from mother import pipeline_utils

model_settings = {
    "feature_selection_flags": [
        "DROP_CORRELATED",
        "DROP_CONSTANT",
        "DROP_DUPLICATES",
        "DROP_UNIMPORTANT",
    ],
    "feature_selection_threshold": 0,
    "correlation_threshold": 0.9,
    "algorithm": "catboost",
    "feature_selection_type": "catboost",
    "model_type": "regression",
    "target_type": "single_target",
}
pipeline_settings = {
    "remainder": "passthrough",
    "verbose_feature_names_out": False,
}

custom_model_step = ml.ColumnTransformerWithHyperparameterRooting(
    transformers=[
        ("custom_string_preprocessor", CustomStringPreprocessor(), ["string_col"]),
        (
            "feature_selector",
            pipeline_utils.get_feature_selection_pipeline(
                settings=model_settings, pipeline_settings=pipeline_settings, cv=cv
            ),
            list(features),
        ),
    ],
    **pipeline_settings,
).set_output(transform="pandas")

Warning: Failed to load model from m_tabpfn: No module named 'torch' (Please, ignore this message if you don't need tabpfn)

In [11]:
model = ml.PipelineWithHyperparameterRooting(
    [
        ("custom_model_step", custom_model_step),
        (
            "ml_model",
            ml.CatboostRegressorMother(target_type="single_target", logging_level="Silent"),
        ),
    ]
)
# fit the model to data

x = pd.concat((features, data["string_col"]), axis=1)

model.fit(x, data["expt"])

targets_pred = model.predict(x)

In [12]:
model["custom_model_step"]["custom_string_preprocessor"]

CustomStringPreprocessor()